### ISSUE TITLE
Core UI: automatically generate `lib/index.tsx` on pre-build

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-cloud#286]
Automatically populate `lib/index` with `lib` components.

**Comment by wirednkod** [comment]
I am not sure if this should be completely automated. My only concern is, if there would/should be internal components that we do not want to export automatically (e.g. the various Buttons if we proceed only with the `<Button type="..." />` as main one instead of the variants) through this automated process; 
Maybe a simple file name can be added to the automated process for "Choose these files to export" kind of (or maybe even better a list of components to exclude - as I expect them to be less)

**Comment by rossbulat** [comment]
On the flip-side, we may want to export all the component separately, and bundle their css into the component on a per-component basis, for projects that do not wish to the the entirety of `core-ui`. In this case we'd probs need 2 rollup build processes.
