### ISSUE TITLE
Launching Polkadot-cloud sandbox on GitHub Pages

### ISSUE THREAD

**Issue by wirednkod** [paritytech/polkadot-cloud#357]
I believe it's a valuable proposition to make the components library more accessible for interested parties and stakeholders. To facilitate this, I think, releasing the components library "sandbox" on the gh-pages branch, would make much sense. This approach would offer the benefit of allowing us, as well as external contributors, to effectively identify and address any issues or bugs without the need of installing and using our components. Furthermore, it serves as a great opportunity for everyone to become acquainted with the existing components, as well as any potential gaps, and provide constructive feedback.

cc @rossbulat @TingALin opinions?

**Comment by rossbulat** [comment]
I'd like to see a fully fledged polished app landing page on gh pages :) (and https://polkadot.cloud).

**Comment by rossbulat** [comment]
Upon reflecting I completely agree. However I feel the sandbox needs completing and improving before we go ahead and launch it. 

Instead of a roadmap, I think this project needs to be very proactive, in that we respond to requests by the community as and when they come.

We provide the platform to host packages and the tooling around publishing them - as long as the community knows this we can be that go-to platform to standardise assets.

**Comment by wirednkod** [comment]
> Instead of a roadmap, I think this project needs to be very proactive, in that we respond to requests by the community as and when they come. A call-to-action instead of a roadmap.

Could not agree more; Our "roadmap" should be the projects we are working on (e.g. polkadot staking and xcm dashboards) and the requests of the community, if any; That been said - to me it means that aforementioned dashboards should be eventually replaced with solely polkadot cloud components (and that would fulfill our first roadmap for the project);
