### ISSUE TITLE
Separate Loaders from core-ui

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-cloud#364]
To prevent bloating the CSS, separate loaders from core UI. 

Would be a good opportunity to use a different postcss process to embed css into each of the respective loader components instead of having one separate css file for the whole package. This will prevent devs from having to import a separate CSS file. If we can successfully trial this here, we can then apply as another core-ui build option.

**Comment by wirednkod** [comment]
Why the loaders need to separate from the core-ui? What is the categorization you have in mind?

Concerning Postcss processes, I think that a process should split css, so that each component should generate and include its own css instead of having 1 big fat css for the whole library. In addition it would be very good to allow the classes auto-generate the name instead of using the one provided by the dev. This will help a LOT with many issues that the library has at the moments (which I will list below):
a) **Treeshaking**: will make each component less heavy (size-wise) for the app that is using it
b) **Collisions**: In a case where a class or specific characteristic is repeated in more than one components that would lead to a collision of classes and thus breaking of 1 or more components; Having auto-generated names, is helping on avoiding that (e.g. instead of `.btn-primary` there will be a `._6BHvsdgfK1kiz89Ytv3wDFH` className across)
c) **Security**: The approach of renaming scss classes during build with random names generated on each release, creates an extra layer of security against scrapper tools;

If you agree with the above, I will be more than happy on taking over these tasks and implement;

What do you think @rossbulat @TingALin ?

**Comment by rossbulat** [comment]
> Why the loaders need to separate from the core-ui?

Core UI should be core structure, I am even thinking of changing the name to dashboard-ui to further limit its scope. None of the loaders are being used in the dashboard, but the CSS is still being added to the output file. Which leads me to the modular CSS point.

> Concerning Postcss processes, I think that a process should split css, so that each component should generate and include its own css instead of having 1 big fat css for the whole library. 

Yes, this is what I suggested in my opening comment and I am researching solutions now. It is not currently built into Rollup or the postcss plugin, but there are workarounds.

**Comment by wirednkod** [comment]
After several discussions and since we re-organised the structure of the repos and split the SCSS to different package, for better tree shaking, I think we can close this issue now. If I am missing something that is not done, please re-open and advice accordingly
